### ISSUE TITLE
How to parse all positive eth addresses?

### ISSUE THREAD

**Issue by band1k1** [oo7ww/eth_block_parser#1]
How to parse all positive eth addresses?

**Comment by oo7ww** [comment]
What do you mean by 'positive'?
If 'positive' means an address has been used in a transaction, you can find it in the blockchain.
If 'positive' means the right format of address, you can generate a lot of them as long as you follow the address generating rules.

**Comment by band1k1** [comment]
I meant that I find the way to get a list of all eth addresses that has ever been used.

**Comment by oo7ww** [comment]
I think you can use geth and web3.js / web3.py to iterate all the blocks to get the from and to,  or maybe etherscan can give you some easy ways like excel files or somekind api to get the addresses you need. Just an advice.
